[package]
name = "sgvr"
version = "0.1.0"
edition = "2024"
default-run = "sgvr"

[dependencies]
rustfft = "6.2"
image = "0.25"
clap = { version = "4.5", features = ["derive"] }
indicatif = "0.17"
hsl = "0.1.1"
symphonia = "0.5.4"
